import type {
  User, Repository, Branch, Commit, PullRequest, Issue,
  Label, Milestone, Pipeline, PipelineJob, Release, Notification, Comment,
  TreeNode, PipelineStage, DeployEnvironment
} from "@/types";

// ── Users ──────────────────────────────────────────────────────────────────
export const CURRENT_USER: User = {
  id: "u1",
  username: "bhavish",
  name: "Bhavish Salian",
  email: "bhavishsalian53@gmail.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bhavish",
  bio: "Building things with code. Open source enthusiast.",
  location: "Mumbai, India",
  website: "https://bhavish.dev",
  company: "@codevault",
  followers: 842,
  following: 219,
  publicRepos: 47,
  createdAt: "2020-03-15T10:00:00Z",
};

export const USERS: User[] = [
  CURRENT_USER,
  {
    id: "u2",
    username: "ananya",
    name: "Ananya Sharma",
    email: "ananya@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ananya",
    bio: "Full-stack developer. Coffee addict.",
    location: "Bangalore, India",
    website: "",
    company: "@codevault",
    followers: 512,
    following: 130,
    publicRepos: 31,
    createdAt: "2021-06-10T08:00:00Z",
  },
  {
    id: "u3",
    username: "rohan",
    name: "Rohan Verma",
    email: "rohan@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rohan",
    bio: "DevOps engineer & cloud architect.",
    location: "Delhi, India",
    website: "",
    company: "",
    followers: 289,
    following: 98,
    publicRepos: 22,
    createdAt: "2019-11-20T12:00:00Z",
  },
  {
    id: "u4",
    username: "priya",
    name: "Priya Nair",
    email: "priya@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    bio: "ML engineer and open source contributor.",
    location: "Chennai, India",
    website: "https://priya.io",
    company: "",
    followers: 1204,
    following: 341,
    publicRepos: 68,
    createdAt: "2018-09-05T09:00:00Z",
  },
];

// ── Labels ─────────────────────────────────────────────────────────────────
export const LABELS: Label[] = [
  { id: "l1", name: "bug", color: "#d73a4a", description: "Something isn't working" },
  { id: "l2", name: "enhancement", color: "#a2eeef", description: "New feature or request" },
  { id: "l3", name: "documentation", color: "#0075ca", description: "Improvements or additions to documentation" },
  { id: "l4", name: "good first issue", color: "#7057ff", description: "Good for newcomers" },
  { id: "l5", name: "help wanted", color: "#008672", description: "Extra attention is needed" },
  { id: "l6", name: "wontfix", color: "#ffffff", description: "This will not be worked on" },
  { id: "l7", name: "duplicate", color: "#cfd3d7", description: "This issue already exists" },
  { id: "l8", name: "question", color: "#d876e3", description: "Further information is requested" },
  { id: "l9", name: "security", color: "#e4e669", description: "Security vulnerability" },
  { id: "l10", name: "performance", color: "#fbca04", description: "Performance improvement" },
];

// ── Milestones ─────────────────────────────────────────────────────────────
export const MILESTONES: Milestone[] = [
  {
    id: "m1",
    number: 1,
    title: "v1.0.0 Release",
    description: "Initial stable release",
    state: "open",
    dueOn: "2026-07-30T00:00:00Z",
    openIssues: 5,
    closedIssues: 18,
    progress: 78,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "m2",
    number: 2,
    title: "v1.1.0 - Auth & Permissions",
    description: "Role-based access control and team management",
    state: "open",
    dueOn: "2026-09-15T00:00:00Z",
    openIssues: 12,
    closedIssues: 4,
    progress: 25,
    createdAt: "2026-03-01T00:00:00Z",
  },
];

// ── Commits ────────────────────────────────────────────────────────────────
export const COMMITS: Commit[] = [
  {
    sha: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    shortSha: "a1b2c3d",
    message: "feat: add pipeline status badges to repository overview",
    body: "Adds real-time pipeline status indicators to the repository header and listing pages.",
    author: USERS[0],
    authoredAt: "2026-06-19T09:00:00Z",
    committedAt: "2026-06-19T09:05:00Z",
    additions: 142,
    deletions: 23,
    filesChanged: 6,
    parents: ["b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3"],
  },
  {
    sha: "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3",
    shortSha: "b2c3d4e",
    message: "fix: resolve race condition in concurrent merge operations",
    body: "",
    author: USERS[1],
    authoredAt: "2026-06-18T16:30:00Z",
    committedAt: "2026-06-18T16:31:00Z",
    additions: 38,
    deletions: 12,
    filesChanged: 3,
    parents: ["c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"],
  },
  {
    sha: "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
    shortSha: "c3d4e5f",
    message: "refactor: extract auth middleware into separate module",
    body: "",
    author: USERS[2],
    authoredAt: "2026-06-17T11:00:00Z",
    committedAt: "2026-06-17T11:01:00Z",
    additions: 210,
    deletions: 185,
    filesChanged: 12,
    parents: ["d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5"],
  },
  {
    sha: "d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5",
    shortSha: "d4e5f6a",
    message: "docs: update API documentation and add examples",
    body: "",
    author: USERS[0],
    authoredAt: "2026-06-16T14:20:00Z",
    committedAt: "2026-06-16T14:21:00Z",
    additions: 87,
    deletions: 15,
    filesChanged: 4,
    parents: [],
  },
  {
    sha: "e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6",
    shortSha: "e5f6a1b",
    message: "test: increase coverage for webhook handlers",
    body: "",
    author: USERS[3],
    authoredAt: "2026-06-15T10:45:00Z",
    committedAt: "2026-06-15T10:46:00Z",
    additions: 320,
    deletions: 0,
    filesChanged: 8,
    parents: [],
  },
];

// ── Branches ───────────────────────────────────────────────────────────────
export const BRANCHES: Branch[] = [
  {
    id: "br1",
    name: "main",
    sha: COMMITS[0].sha,
    isDefault: true,
    isProtected: true,
    aheadBy: 0,
    behindBy: 0,
    lastCommit: COMMITS[0],
    author: USERS[0],
    updatedAt: "2026-06-19T09:05:00Z",
  },
  {
    id: "br2",
    name: "develop",
    sha: COMMITS[1].sha,
    isDefault: false,
    isProtected: true,
    aheadBy: 3,
    behindBy: 1,
    lastCommit: COMMITS[1],
    author: USERS[1],
    updatedAt: "2026-06-18T16:31:00Z",
  },
  {
    id: "br3",
    name: "feature/pipeline-ui",
    sha: COMMITS[2].sha,
    isDefault: false,
    isProtected: false,
    aheadBy: 7,
    behindBy: 2,
    lastCommit: COMMITS[2],
    author: USERS[2],
    updatedAt: "2026-06-17T11:01:00Z",
  },
  {
    id: "br4",
    name: "fix/merge-race-condition",
    sha: COMMITS[3].sha,
    isDefault: false,
    isProtected: false,
    aheadBy: 1,
    behindBy: 5,
    lastCommit: COMMITS[3],
    author: USERS[1],
    updatedAt: "2026-06-16T14:21:00Z",
  },
  {
    id: "br5",
    name: "chore/update-dependencies",
    sha: COMMITS[4].sha,
    isDefault: false,
    isProtected: false,
    aheadBy: 2,
    behindBy: 8,
    lastCommit: COMMITS[4],
    author: USERS[3],
    updatedAt: "2026-06-15T10:46:00Z",
  },
];

// ── File Tree ──────────────────────────────────────────────────────────────
export const FILE_TREE: TreeNode[] = [
  { name: ".github", path: ".github", type: "tree", sha: "abc001", lastCommit: "ci: add GitHub Actions workflow", lastCommitDate: "2026-06-10T00:00:00Z" },
  { name: "docs", path: "docs", type: "tree", sha: "abc002", lastCommit: "docs: update API reference", lastCommitDate: "2026-06-16T00:00:00Z" },
  { name: "src", path: "src", type: "tree", sha: "abc003", lastCommit: "refactor: extract auth middleware", lastCommitDate: "2026-06-17T00:00:00Z" },
  { name: "tests", path: "tests", type: "tree", sha: "abc004", lastCommit: "test: increase coverage", lastCommitDate: "2026-06-15T00:00:00Z" },
  { name: ".env.example", path: ".env.example", type: "file", size: 512, sha: "abc005", lastCommit: "chore: add env example", lastCommitDate: "2026-05-01T00:00:00Z" },
  { name: ".gitignore", path: ".gitignore", type: "file", size: 1024, sha: "abc006", lastCommit: "init: project setup", lastCommitDate: "2026-01-01T00:00:00Z" },
  { name: "CHANGELOG.md", path: "CHANGELOG.md", type: "file", size: 4096, sha: "abc007", lastCommit: "docs: update changelog", lastCommitDate: "2026-06-18T00:00:00Z" },
  { name: "LICENSE", path: "LICENSE", type: "file", size: 1096, sha: "abc008", lastCommit: "init: add MIT license", lastCommitDate: "2026-01-01T00:00:00Z" },
  { name: "package.json", path: "package.json", type: "file", size: 2048, sha: "abc009", lastCommit: "chore: update dependencies", lastCommitDate: "2026-06-15T00:00:00Z" },
  { name: "README.md", path: "README.md", type: "file", size: 8192, sha: "abc010", lastCommit: "docs: update README with new features", lastCommitDate: "2026-06-19T00:00:00Z" },
  { name: "tsconfig.json", path: "tsconfig.json", type: "file", size: 768, sha: "abc011", lastCommit: "chore: strict TypeScript config", lastCommitDate: "2026-03-20T00:00:00Z" },
];

// ── Pull Requests ──────────────────────────────────────────────────────────
export const PULL_REQUESTS: PullRequest[] = [
  {
    id: "pr1",
    number: 42,
    title: "feat: Add CI/CD pipeline dashboard with real-time status",
    body: "## Summary\nThis PR adds a comprehensive CI/CD pipeline dashboard that shows real-time build statuses, logs, and deployment history.\n\n## Changes\n- New pipeline list view\n- Job-level log streaming\n- Status badges on repo overview\n\n## Testing\n- Added unit tests for pipeline status reducer\n- E2E tests for pipeline page\n\nFixes #38",
    state: "open",
    author: USERS[0],
    assignees: [USERS[1]],
    reviewers: [USERS[2], USERS[3]],
    labels: [LABELS[1], LABELS[9]],
    milestone: MILESTONES[0],
    sourceBranch: "feature/pipeline-ui",
    targetBranch: "main",
    commits: 7,
    additions: 842,
    deletions: 123,
    filesChanged: 18,
    comments: 6,
    reviewComments: 14,
    approvals: 1,
    changesRequested: 0,
    createdAt: "2026-06-15T09:00:00Z",
    updatedAt: "2026-06-19T08:30:00Z",
    isDraft: false,
    isMergeable: true,
  },
  {
    id: "pr2",
    number: 41,
    title: "fix: resolve race condition in concurrent merge operations",
    body: "Fixes a critical race condition that could corrupt the merge history when two PRs were merged simultaneously.\n\nFixes #39, #40",
    state: "merged",
    author: USERS[1],
    assignees: [USERS[0]],
    reviewers: [USERS[0]],
    labels: [LABELS[0]],
    milestone: MILESTONES[0],
    sourceBranch: "fix/merge-race-condition",
    targetBranch: "main",
    commits: 1,
    additions: 38,
    deletions: 12,
    filesChanged: 3,
    comments: 2,
    reviewComments: 5,
    approvals: 2,
    changesRequested: 0,
    mergedAt: "2026-06-18T17:00:00Z",
    createdAt: "2026-06-17T10:00:00Z",
    updatedAt: "2026-06-18T17:00:00Z",
    isDraft: false,
    isMergeable: false,
  },
  {
    id: "pr3",
    number: 40,
    title: "WIP: refactor authentication system",
    body: "Refactoring the auth module. Not ready for review yet.",
    state: "open",
    author: USERS[2],
    assignees: [],
    reviewers: [],
    labels: [LABELS[4]],
    milestone: MILESTONES[1],
    sourceBranch: "refactor/auth",
    targetBranch: "develop",
    commits: 3,
    additions: 210,
    deletions: 185,
    filesChanged: 12,
    comments: 0,
    reviewComments: 0,
    approvals: 0,
    changesRequested: 0,
    createdAt: "2026-06-17T11:00:00Z",
    updatedAt: "2026-06-17T11:00:00Z",
    isDraft: true,
    isMergeable: true,
  },
  {
    id: "pr4",
    number: 39,
    title: "docs: Improve API documentation with examples and guides",
    body: "Adds comprehensive API documentation including:\n- Authentication guide\n- Rate limiting explanation\n- Code examples in 5 languages\n- Error reference",
    state: "open",
    author: USERS[3],
    assignees: [USERS[0]],
    reviewers: [USERS[0], USERS[1]],
    labels: [LABELS[2], LABELS[3]],
    sourceBranch: "docs/api-docs",
    targetBranch: "main",
    commits: 4,
    additions: 1240,
    deletions: 89,
    filesChanged: 22,
    comments: 8,
    reviewComments: 3,
    approvals: 2,
    changesRequested: 0,
    createdAt: "2026-06-14T15:00:00Z",
    updatedAt: "2026-06-19T07:00:00Z",
    isDraft: false,
    isMergeable: true,
  },
];

// ── Issues ─────────────────────────────────────────────────────────────────
export const ISSUES: Issue[] = [
  {
    id: "i1",
    number: 55,
    title: "Pipeline logs not showing for long-running jobs",
    body: "When a job runs for more than 10 minutes, the log stream disconnects and only shows partial output.\n\n**Steps to reproduce:**\n1. Create a job that takes > 10 min\n2. Open the pipeline detail page\n3. Observe log stream stops\n\n**Expected:** Full log output\n**Actual:** Log cuts off at ~10 min mark",
    state: "open",
    author: USERS[1],
    assignees: [USERS[0]],
    labels: [LABELS[0], LABELS[8]],
    milestone: MILESTONES[0],
    comments: 5,
    reactions: { thumbsUp: 12, thumbsDown: 0, laugh: 0, hooray: 0, confused: 3, heart: 2, rocket: 4, eyes: 6 },
    isPinned: true,
    isLocked: false,
    createdAt: "2026-06-18T10:00:00Z",
    updatedAt: "2026-06-19T08:00:00Z",
  },
  {
    id: "i2",
    number: 54,
    title: "Add support for OIDC-based runner registration",
    body: "Currently, CI runners must use long-lived tokens. We should add support for OIDC-based runner authentication for better security.",
    state: "open",
    author: USERS[3],
    assignees: [],
    labels: [LABELS[1], LABELS[4], LABELS[8]],
    milestone: MILESTONES[1],
    comments: 8,
    reactions: { thumbsUp: 24, thumbsDown: 0, laugh: 0, hooray: 3, confused: 0, heart: 5, rocket: 12, eyes: 9 },
    isPinned: false,
    isLocked: false,
    createdAt: "2026-06-16T14:00:00Z",
    updatedAt: "2026-06-18T09:00:00Z",
  },
  {
    id: "i3",
    number: 53,
    title: "Webhook delivery retries on failure",
    body: "If a webhook endpoint returns a non-2xx status, the system should retry with exponential backoff instead of marking it as failed immediately.",
    state: "open",
    author: USERS[2],
    assignees: [USERS[2]],
    labels: [LABELS[1], LABELS[9]],
    milestone: MILESTONES[0],
    comments: 3,
    reactions: { thumbsUp: 8, thumbsDown: 0, laugh: 0, hooray: 0, confused: 1, heart: 0, rocket: 3, eyes: 2 },
    isPinned: false,
    isLocked: false,
    createdAt: "2026-06-15T08:30:00Z",
    updatedAt: "2026-06-17T11:00:00Z",
  },
  {
    id: "i4",
    number: 52,
    title: "Dark mode flickers on initial page load",
    body: "The page briefly shows light mode before switching to dark mode, causing a flash of white.",
    state: "closed",
    stateReason: "completed",
    author: USERS[0],
    assignees: [USERS[1]],
    labels: [LABELS[0]],
    comments: 4,
    reactions: { thumbsUp: 6, thumbsDown: 0, laugh: 2, hooray: 0, confused: 0, heart: 1, rocket: 0, eyes: 3 },
    isPinned: false,
    isLocked: false,
    createdAt: "2026-06-12T09:00:00Z",
    updatedAt: "2026-06-14T16:00:00Z",
    closedAt: "2026-06-14T16:00:00Z",
  },
  {
    id: "i5",
    number: 51,
    title: "Add keyboard shortcuts for common actions",
    body: "Power users would benefit from keyboard shortcuts for:\n- `g d` → Go to dashboard\n- `g r` → Go to repos\n- `/` → Focus search\n- `c` → Create new issue/PR",
    state: "open",
    author: USERS[3],
    assignees: [],
    labels: [LABELS[1], LABELS[3]],
    milestone: MILESTONES[1],
    comments: 11,
    reactions: { thumbsUp: 31, thumbsDown: 0, laugh: 0, hooray: 4, confused: 0, heart: 7, rocket: 15, eyes: 12 },
    isPinned: false,
    isLocked: false,
    createdAt: "2026-06-10T13:00:00Z",
    updatedAt: "2026-06-16T10:00:00Z",
  },
];

// ── Pipeline stages ────────────────────────────────────────────────────────
function makeStages(status: string): PipelineStage[] {
  const jobStatus = (s: string) => s as PipelineJob["status"];
  return [
    {
      id: "s1",
      name: "build",
      status: status === "pending" ? "pending" : "success",
      jobs: [
        { id: "j1", name: "build:compile", stage: "build", status: "success", duration: 48, startedAt: "2026-06-19T09:00:00Z", finishedAt: "2026-06-19T09:00:48Z", runner: "runner-01" },
        { id: "j2", name: "build:lint", stage: "build", status: "success", duration: 23, startedAt: "2026-06-19T09:00:00Z", finishedAt: "2026-06-19T09:00:23Z", runner: "runner-02" },
      ],
    },
    {
      id: "s2",
      name: "test",
      status: jobStatus(status === "failed" ? "failed" : status === "pending" ? "pending" : status === "running" ? "running" : "success"),
      jobs: [
        { id: "j3", name: "test:unit", stage: "test", status: jobStatus(status === "failed" ? "failed" : status === "pending" ? "pending" : "success"), duration: status === "failed" ? 12 : 124, runner: "runner-03" },
        { id: "j4", name: "test:integration", stage: "test", status: jobStatus(status === "pending" ? "pending" : status === "running" ? "running" : "success"), duration: 203, runner: "runner-04" },
        { id: "j5", name: "test:e2e", stage: "test", status: "success", duration: 345, runner: "runner-01" },
      ],
    },
    {
      id: "s3",
      name: "deploy",
      status: jobStatus(["success"].includes(status) ? "success" : "pending"),
      jobs: [
        { id: "j6", name: "deploy:staging", stage: "deploy", status: jobStatus(status === "success" ? "success" : "pending"), duration: 67, runner: "runner-deploy" },
        { id: "j7", name: "deploy:production", stage: "deploy", status: jobStatus(status === "success" ? "success" : "pending"), duration: 92, runner: "runner-deploy" },
      ],
    },
  ];
}

export const PIPELINES: Pipeline[] = [
  {
    id: "p1",
    number: 148,
    status: "success",
    ref: "main",
    sha: COMMITS[0].sha,
    source: "push",
    commit: COMMITS[0],
    stages: makeStages("success"),
    duration: 542,
    createdAt: "2026-06-19T09:00:00Z",
    updatedAt: "2026-06-19T09:09:02Z",
    finishedAt: "2026-06-19T09:09:02Z",
    triggeredBy: USERS[0],
  },
  {
    id: "p2",
    number: 147,
    status: "failed",
    ref: "feature/pipeline-ui",
    sha: COMMITS[1].sha,
    source: "pull_request",
    commit: COMMITS[1],
    stages: makeStages("failed"),
    duration: 83,
    createdAt: "2026-06-18T16:30:00Z",
    updatedAt: "2026-06-18T16:31:23Z",
    finishedAt: "2026-06-18T16:31:23Z",
    triggeredBy: USERS[1],
  },
  {
    id: "p3",
    number: 146,
    status: "running",
    ref: "develop",
    sha: COMMITS[2].sha,
    source: "push",
    commit: COMMITS[2],
    stages: makeStages("running"),
    createdAt: "2026-06-19T09:15:00Z",
    updatedAt: "2026-06-19T09:18:00Z",
    triggeredBy: USERS[2],
  },
  {
    id: "p4",
    number: 145,
    status: "success",
    ref: "main",
    sha: COMMITS[3].sha,
    source: "schedule",
    commit: COMMITS[3],
    stages: makeStages("success"),
    duration: 481,
    createdAt: "2026-06-18T00:00:00Z",
    updatedAt: "2026-06-18T00:08:01Z",
    finishedAt: "2026-06-18T00:08:01Z",
    triggeredBy: USERS[0],
  },
  {
    id: "p5",
    number: 144,
    status: "canceled",
    ref: "chore/update-dependencies",
    sha: COMMITS[4].sha,
    source: "push",
    commit: COMMITS[4],
    stages: makeStages("canceled"),
    duration: 31,
    createdAt: "2026-06-17T14:00:00Z",
    updatedAt: "2026-06-17T14:00:31Z",
    finishedAt: "2026-06-17T14:00:31Z",
    triggeredBy: USERS[3],
  },
];

// ── Releases ───────────────────────────────────────────────────────────────
export const RELEASES: Release[] = [
  {
    id: "r1",
    tagName: "v0.9.0",
    name: "v0.9.0 – Pipeline & Webhooks",
    body: "## What's New\n\n### Features\n- ✨ CI/CD pipeline dashboard\n- 🪝 Webhook delivery with retry\n- 📊 Repository insights & analytics\n\n### Bug Fixes\n- 🐛 Fixed dark mode flash on load\n- 🐛 Resolved concurrent merge race condition\n\n### Breaking Changes\n- The `/api/v1/pipelines` endpoint has been renamed to `/api/v1/repos/:id/pipelines`\n\nFull changelog: [CHANGELOG.md](./CHANGELOG.md)",
    isDraft: false,
    isPreRelease: false,
    author: USERS[0],
    assets: [
      { id: "a1", name: "gitcode-v0.9.0-linux-amd64.tar.gz", size: 18432000, downloadCount: 1204, contentType: "application/gzip", url: "#" },
      { id: "a2", name: "gitcode-v0.9.0-darwin-arm64.tar.gz", size: 16384000, downloadCount: 892, contentType: "application/gzip", url: "#" },
      { id: "a3", name: "gitcode-v0.9.0-windows-amd64.zip", size: 21504000, downloadCount: 673, contentType: "application/zip", url: "#" },
      { id: "a4", name: "Source code (zip)", size: 4096000, downloadCount: 341, contentType: "application/zip", url: "#" },
    ],
    createdAt: "2026-06-10T12:00:00Z",
    publishedAt: "2026-06-10T12:30:00Z",
    targetCommitish: "main",
  },
  {
    id: "r2",
    tagName: "v0.8.2",
    name: "v0.8.2 – Security Patch",
    body: "## Security Fix\n\nThis release patches a critical SSRF vulnerability in the webhook handler. All users are encouraged to upgrade immediately.\n\nCVE: CVE-2026-1234 (CVSS 8.6 - High)",
    isDraft: false,
    isPreRelease: false,
    author: USERS[0],
    assets: [
      { id: "a5", name: "gitcode-v0.8.2-linux-amd64.tar.gz", size: 17408000, downloadCount: 3891, contentType: "application/gzip", url: "#" },
    ],
    createdAt: "2026-05-28T10:00:00Z",
    publishedAt: "2026-05-28T10:15:00Z",
    targetCommitish: "main",
  },
  {
    id: "r3",
    tagName: "v1.0.0-beta.1",
    name: "v1.0.0 Beta 1",
    body: "First beta release toward v1.0.0. Not production ready.\n\n## New in Beta 1\n- Complete RBAC system\n- Organization-level pipelines\n- Advanced search with filters",
    isDraft: false,
    isPreRelease: true,
    author: USERS[0],
    assets: [],
    createdAt: "2026-06-19T07:00:00Z",
    publishedAt: "2026-06-19T07:30:00Z",
    targetCommitish: "develop",
  },
];

// ── Repositories ───────────────────────────────────────────────────────────
export const REPOSITORIES: Repository[] = [
  {
    id: "repo1",
    name: "gitcode",
    fullName: "bhavish/gitcode",
    owner: USERS[0],
    description: "A self-hosted Git repository management platform with CI/CD, issues, and wikis.",
    isPrivate: false,
    isForked: false,
    language: "TypeScript",
    languages: { TypeScript: 68, CSS: 18, JavaScript: 10, Shell: 4 },
    stars: 2847,
    forks: 312,
    watchers: 189,
    openIssues: 12,
    openPRs: 4,
    defaultBranch: "main",
    topics: ["git", "devops", "ci-cd", "self-hosted", "typescript"],
    license: "MIT",
    size: 48200,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-19T09:05:00Z",
    pushedAt: "2026-06-19T09:05:00Z",
  },
  {
    id: "repo2",
    name: "api-gateway",
    fullName: "bhavish/api-gateway",
    owner: USERS[0],
    description: "High-performance API gateway with rate limiting, auth, and observability.",
    isPrivate: false,
    isForked: false,
    language: "Go",
    languages: { Go: 91, Dockerfile: 5, Shell: 4 },
    stars: 1203,
    forks: 87,
    watchers: 64,
    openIssues: 5,
    openPRs: 2,
    defaultBranch: "main",
    topics: ["api-gateway", "go", "microservices", "rate-limiting"],
    license: "Apache-2.0",
    size: 22100,
    createdAt: "2025-08-15T00:00:00Z",
    updatedAt: "2026-06-17T12:00:00Z",
    pushedAt: "2026-06-17T12:00:00Z",
  },
  {
    id: "repo3",
    name: "ml-pipeline",
    fullName: "bhavish/ml-pipeline",
    owner: USERS[0],
    description: "Distributed ML training pipeline with experiment tracking.",
    isPrivate: true,
    isForked: false,
    language: "Python",
    languages: { Python: 84, Jupyter: 12, YAML: 4 },
    stars: 0,
    forks: 0,
    watchers: 3,
    openIssues: 7,
    openPRs: 1,
    defaultBranch: "main",
    topics: ["machine-learning", "python", "distributed"],
    license: "MIT",
    size: 15600,
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2026-06-15T08:00:00Z",
    pushedAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "repo4",
    name: "react-ui-kit",
    fullName: "ananya/react-ui-kit",
    owner: USERS[1],
    description: "Accessible React component library with Tailwind CSS variants.",
    isPrivate: false,
    isForked: false,
    language: "TypeScript",
    languages: { TypeScript: 75, CSS: 20, JavaScript: 5 },
    stars: 4512,
    forks: 521,
    watchers: 342,
    openIssues: 23,
    openPRs: 8,
    defaultBranch: "main",
    topics: ["react", "ui", "components", "tailwind", "accessibility"],
    license: "MIT",
    size: 31200,
    createdAt: "2025-04-10T00:00:00Z",
    updatedAt: "2026-06-19T06:00:00Z",
    pushedAt: "2026-06-19T06:00:00Z",
  },
  {
    id: "repo5",
    name: "k8s-operator",
    fullName: "rohan/k8s-operator",
    owner: USERS[2],
    description: "Kubernetes operator for managing stateful workloads at scale.",
    isPrivate: false,
    isForked: false,
    language: "Go",
    languages: { Go: 88, YAML: 10, Shell: 2 },
    stars: 892,
    forks: 143,
    watchers: 87,
    openIssues: 9,
    openPRs: 3,
    defaultBranch: "main",
    topics: ["kubernetes", "operator", "go", "cloud-native"],
    license: "Apache-2.0",
    size: 18900,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-06-18T14:00:00Z",
    pushedAt: "2026-06-18T14:00:00Z",
  },
];

// ── Notifications ──────────────────────────────────────────────────────────
export const NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "review", title: "ananya requested your review", body: "on PR #42 feat: Add CI/CD pipeline dashboard", repo: "bhavish/gitcode", url: "/bhavish/gitcode/pulls/42", isRead: false, createdAt: "2026-06-19T08:30:00Z" },
  { id: "n2", type: "mention", title: "rohan mentioned you", body: "in issue #55 Pipeline logs not showing", repo: "bhavish/gitcode", url: "/bhavish/gitcode/issues/55", isRead: false, createdAt: "2026-06-19T07:15:00Z" },
  { id: "n3", type: "pipeline", title: "Pipeline #148 succeeded", body: "on branch main — 9m 2s", repo: "bhavish/gitcode", url: "/bhavish/gitcode/pipelines/p1", isRead: false, createdAt: "2026-06-19T09:09:00Z" },
  { id: "n4", type: "pipeline", title: "Pipeline #147 failed", body: "on branch feature/pipeline-ui — test:unit failed", repo: "bhavish/gitcode", url: "/bhavish/gitcode/pipelines/p2", isRead: true, createdAt: "2026-06-18T16:31:00Z" },
  { id: "n5", type: "pull_request", title: "priya commented on PR #39", body: "\"The examples are great, but we need to add rate limit docs\"", repo: "bhavish/gitcode", url: "/bhavish/gitcode/pulls/39", isRead: true, createdAt: "2026-06-19T07:00:00Z" },
  { id: "n6", type: "issue", title: "New issue assigned to you", body: "#55 Pipeline logs not showing for long-running jobs", repo: "bhavish/gitcode", url: "/bhavish/gitcode/issues/55", isRead: true, createdAt: "2026-06-18T10:05:00Z" },
];

// ── Comments ───────────────────────────────────────────────────────────────
export const COMMENTS: Comment[] = [
  {
    id: "c1",
    body: "This is a great addition! The pipeline dashboard is much needed. One concern: will this scale for repos with 1000+ pipelines? We might need pagination from day one.",
    author: USERS[1],
    reactions: { thumbsUp: 4, thumbsDown: 0, laugh: 0, hooray: 0, confused: 0, heart: 2, rocket: 0, eyes: 1 },
    createdAt: "2026-06-16T10:00:00Z",
    updatedAt: "2026-06-16T10:00:00Z",
    isEdited: false,
  },
  {
    id: "c2",
    body: "Pagination is handled server-side. The initial page loads 25 pipelines, and we use cursor-based pagination for subsequent loads. See `src/api/pipelines.ts:42`.",
    author: USERS[0],
    reactions: { thumbsUp: 2, thumbsDown: 0, laugh: 0, hooray: 0, confused: 0, heart: 0, rocket: 1, eyes: 0 },
    createdAt: "2026-06-16T11:00:00Z",
    updatedAt: "2026-06-16T11:00:00Z",
    isEdited: false,
  },
  {
    id: "c3",
    body: "Could we also add a \"re-run failed jobs only\" option? That would save a lot of time when only the flaky e2e tests fail.",
    author: USERS[2],
    reactions: { thumbsUp: 8, thumbsDown: 0, laugh: 0, hooray: 1, confused: 0, heart: 1, rocket: 3, eyes: 2 },
    createdAt: "2026-06-17T09:00:00Z",
    updatedAt: "2026-06-17T09:00:00Z",
    isEdited: false,
  },
];

// ── Deploy Environments ────────────────────────────────────────────────────
export const ENVIRONMENTS: DeployEnvironment[] = [
  {
    id: "e1",
    name: "production",
    url: "https://gitcode.io",
    state: "active",
    lastDeployment: {
      sha: COMMITS[0].shortSha,
      createdAt: "2026-06-19T09:09:02Z",
      deployedBy: USERS[0],
    },
  },
  {
    id: "e2",
    name: "staging",
    url: "https://staging.gitcode.io",
    state: "active",
    lastDeployment: {
      sha: COMMITS[0].shortSha,
      createdAt: "2026-06-19T09:09:00Z",
      deployedBy: USERS[0],
    },
  },
  {
    id: "e3",
    name: "review/pipeline-ui",
    url: "https://review-pipeline-ui.gitcode.io",
    state: "active",
    lastDeployment: {
      sha: COMMITS[2].shortSha,
      createdAt: "2026-06-17T11:05:00Z",
      deployedBy: USERS[2],
    },
  },
];

// ── Trending repos (explore page) ──────────────────────────────────────────
export const TRENDING_REPOS = [...REPOSITORIES].sort((a, b) => b.stars - a.stars);
